eyes that follow
you-dont-need/You-Dont-Need-JavaScript pull request #116
Opened 2022-10-03 09:59 UTC by starohit

added a new css animation

2023-09-03 03:39 UTC, cht8687 commented on examples/eyes-that-follow.html
> +            document.querySelector('body').addEventListener('mousemove',eyeball);
is this....javascript? 😄

2023-10-19 07:01 UTC, gaurovgiri requested changes

2023-10-19 07:01 UTC, gaurovgiri commented on examples/eyes-that-follow.html
> +          <script>
Sorry, you can't use javascript :(

2023-10-22 22:14 UTC, aayush105 reviewed
@starohit you can't use JS  in this repository.

2023-10-22 22:14 UTC, closed without merging