RGBcolorgame.css
you-dont-need/You-Dont-Need-JavaScript pull request #291
Opened 2023-10-21 10:12 UTC by RS-labhub

2023-10-21 13:41 UTC, gaurovgiri requested changes
Please provide html file as well.

2023-10-21 14:21 UTC, RS-labhub commented
> Please provide html file as well.

Providing

2023-10-21 14:55 UTC, aayush105 reviewed
@RS-labhub add the output of your code in image folder as well as in the README.md file and push it again.

2023-10-21 14:55 UTC, aayush105 commented on RGBcolorgame.css
> +body {
@RS-labhub HTML code is missing here so update your code and add the output of your code in image folder as well as in the README.md file and push it again.

2023-10-21 15:04 UTC, RS-labhub commented
> @RS-labhub add the output of your code in image folder as well as in the README.md file and push it again.

Okayyyy...

2023-10-21 15:16 UTC, RS-labhub commented on RGBcolorgame.css
> +body {
Done!

2023-10-21 17:33 UTC, RS-labhub commented
> @RS-labhub add the output of your code in image folder as well as in the README.md file and push it again.

@aayush105 please take a look. Other files are uploaded from another patch unknowingly.

2023-10-21 18:42 UTC, aayush105 commented
> > @RS-labhub add the output of your code in image folder as well as in the README.md file and push it again.
> 
> @aayush105 please take a look. Other files are uploaded from another patch unknowingly.

Dont add in such way add all in same PR. This time i will merge but from next time it will not be merged.
Thank you!

2023-10-22 04:13 UTC, RS-labhub commented
> > > @RS-labhub add the output of your code in image folder as well as in the README.md file and push it again.
> > 
> > 
> > @aayush105 please take a look. Other files are uploaded from another patch unknowingly.
> 
> Dont add in such way add all in same PR. This time i will merge but from next time it will not be merged. Thank you!

Thank you! I'll take care from the next time... Thank you so much!

2023-10-22 06:09 UTC, merged