Update README.MD
you-dont-need/You-Dont-Need-JavaScript pull request #83
Opened 2020-09-30 16:32 UTC by abrar78

Have corrected the counting into the readme file and write little more description.

2021-05-15 07:43 UTC, naderalfakesh approved these changes

2021-05-16 18:13 UTC, KOLANICH requested changes

2021-05-16 18:13 UTC, KOLANICH commented on README.MD
> +#these css files contain various effects and animations without JS.
A text before the title is not needed.

2021-05-16 18:13 UTC, KOLANICH commented on README.MD
> +2. [Carousel](#Carousel)
`1.` requires no maintaince. GH numerates list items itself. It also has `#.` notation for them, so no misinformation like `1.` in the plain text form.

2023-10-22 22:09 UTC, closed without merging